### ISSUE TITLE
@ts-strict in one file triggering strict in others

### ISSUE THREAD

**Issue by sudall** [allegro/typescript-strict-plugin#2]
Hello and thanks for making this cool plugin!

It seems that `//@ts-strict` in one file is causing strict errors to show up in all of the others (that don't have `//@ts-strict`) right after you switch away from looking at the file that has `//@ts-strict`. I have to modify and save a file that doesn't have `//@ts-strict` in order for the errors to go away. I'm using the latest webstorm and TS `3.9.7`. Anything I can do to prevent this? Or is this a bug?

Edit: looks like the same thing happens in vscode

**Comment by sudall** [comment]
I also just discovered that if a file with `//@ts-strict` is open in a separate window (so a file with `//@ts-strict` and one without are open side by side), the errors will never really go away in the file without `//@ts-strict` until I close the `//@ts-strict` file.

**Comment by KostkaBrukowa** [comment]
Hello!
Thank you for finding this problem. This was indeed bug in our code, that came from the fact that when we were changing project settings we were checking if strict mode was already on, but the option was not refreshed immediately, so strict mode was not turned off after getting semantic errors. This issue should be fixed in the next version.

Thank you again!

**Comment by KostkaBrukowa** [comment]
Hey @sudall !
1.0.1 version was just released. You'd like you can check if if works well now. Thanks

**Comment by sudall** [comment]
> Hey @sudall !
> 1.0.1 version was just released. You'd like you can check if if works well now. Thanks

Seems to be working great! thank you! I'll let you know if I find anything else
