### ISSUE TITLE
tsc-strict does not work with emitDeclarationOnly and build option.

### ISSUE THREAD

**Issue by mathieutu** [allegro/typescript-strict-plugin#25]
Hi,

Because `tsc-strict` ends up to run `tsc --strict --noEmit ...process.argv.slice(2)`: 

- it's not compatible with --build option:
```sh
tsc-strict -b apps/fr-app/tsconfig.json
🎯 Found 10794 strict files
⠸ Compiling with strict mode...💥 Typescript did not compile due to some errors. Errors:  [
  "error TS6369: Option '--build' must be the first command line argument."
``` 

- it's not compatible with `emitDeclarationOnly` option:
```sh
λ › tsc-strict
🎯 Found 10794 strict files
⠴ Compiling with strict mode...💥 Typescript did not compile due to some errors. Errors:  [
  "error TS5053: Option 'emitDeclarationOnly' cannot be specified with option 'noEmit'."
]
```
 
Maybe passing the process.argv before strict could be enough for the build option, but I don't know if the noEmit option is really required.

Also, for the record, I've a project with 13106 ts files, and tsc-strict is very longer than tsc (mainly because of the Looking for strict files step). Maybe a cache could be considered?

I'm ready to do the PR when we agree on what to do.

Thanks for your package!

**Comment by mathieutu** [comment]
Hum actually `--strict` seems to not work with `build` at all. Investigating on that.
And for the `emitDeclarationOnly`, we can add `--emitDeclarationOnly false`

**Comment by KostkaBrukowa** [comment]
About putting `...process.argv.slice(2)` makes more sense I guess and I think it would solve the issue with `first command line argument`.
I believe that `noEmit` option makes the plugin run a bit faster (if `noEmit` is set to false in tsconfig), because we don't really need the file output and we only care about errors
The idea about cache is really great and it would actually speed up the process of `tsc-scrict` by 50%. I found the `--listFiles` option for the `tsc` and we would actually need to run `tsc` once and the difference between `tsc-strict` and `tsc` would be negligible. I'll make a PR for it.

Thanks for investigating

**Comment by KostkaBrukowa** [comment]
Btw. 13000 ts files is hell a lot :D

**Comment by KostkaBrukowa** [comment]
And about the `noEmit` flag I'm wondering what to do. Initially I've added the `noEmit` flag, because some project use babel to compile their projects and they don't have `noEmit` flag in their `tsconfig`. Without this flag running `tsconfig` would generate bunch of `js` files unnecessarily. So we have two options:
1. Remove `noEmit` resulting in scenario above
2. Leave like it is now resulting in error with compilation with `tsconfig` provided by you
3. Search `tsconfig` and find if `emitDeclarationOnly` is present and don't add `noEmit` when it is

I think option 3 would be the best in this case, but I'm worring that there would be more cases like that with different flags. What do you think?

**Comment by mathieutu** [comment]
Actually I think that we can leave the noEmit like this, and let devs add `--emitDeclarationOnly false` if they need.
Also, I found out that the build option is not compatible with any config via console option (including strict), so no need to move anything.

Thanks for the cache thing!

>13000 ts files
yep, and it's only the front 😅
