### ISSUE TITLE
VSCode IDE support

### ISSUE THREAD

**Issue by marcomoonpay** [allegro/typescript-strict-plugin#29]
Hi, I'm not sure this is really the place to ask, but I'll give it a try. I wanted to ask you if this TS plugin is supposed to support VSCode out of the box or it requires some special configuration. 

Here's what I see in VSCode, the following file has not been marked as non-strict into my project
![Screen Shot 2022-02-14 at 13 31 43](https://user-images.githubusercontent.com/92251503/153865100-42ef2264-4696-4d3f-aa20-13f324a251b6.png)

And here's what I see in Webstorm (desired behavior). Error if the file has not been marked as non-strict into my project
![Screen Shot 2022-02-14 at 13 32 01](https://user-images.githubusercontent.com/92251503/153865112-14a3385a-4fac-4efb-8824-4789c67b4d80.png)

No error on the contrary
![Screen Shot 2022-02-14 at 13 32 39](https://user-images.githubusercontent.com/92251503/153865109-cf26e35e-a223-4d4d-b861-5e5fdfa1a210.png)

**Comment by KostkaBrukowa** [comment]
I would guess the same issue as in https://github.com/allegro/typescript-strict-plugin/issues/5#issuecomment-882106427
I think we need to add this issue to readme

**Comment by KostkaBrukowa** [comment]
But basically 
VSCode supports this plugin out of the box. However VScode sometimes uses its own typescript version, not the project one - resulting in not reading local tsconfig. If you are using VSCode be sure to have `Use workspace version` option selected instead of `Use VS Code version`. This options can be found by opening the [command pallete](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and selecting `Typescript: Select Typescript Version...`


<img width="729" alt="image" src="https://user-images.githubusercontent.com/35625949/153884371-e0f488d4-05b8-4b88-93d2-1caa7e6081f7.png">

**Comment by marcomoonpay** [comment]
Perfect! It works, thanks a million!
